//@version=3
study("HA Flip", overlay = true)

ha_ticker = heikinashi(tickerid)
hao = security(ha_ticker, period, open)
hac = security(ha_ticker, period, close)

long_cond = hao < hac and hao[1] > hac[1]
short_cond = hao > hac and hao[1] < hac[1]

plotshape(long_cond, style = shape.arrowup,   location = location.belowbar, color = green)
plotshape(short_cond, style = shape.arrowdown, location = location.abovebar, color = red)
